name: Smoke Test

on:
  repository_dispatch:
    types:
      - "vercel.deployment.ready"

run-name: Vercel Deployment Event - ${{ github.event.client_payload.project.name }} (${{ github.event.client_payload.state.type }})

jobs:
  validate-deployment-workflow:
    runs-on: ubuntu-latest
    if: github.event.client_payload.environment == 'production'

    steps:
      - name: 'notify vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: "Vercel - express-curl-demo-days: e2e"
         
      - name: Fetch and validate URL
        id: result
        run: |
          set -e
          URL="${{ github.event.client_payload.url }}"
          echo "Testing URL: $URL"

          STATUS_CODE=$(curl -s -L -o response.txt -w "%{http_code}" -H "x-vercel-protection-bypass: b6QFuzUxEk0cuKELcGDMaMMfPGjpUf7Z" "$URL")
          echo "status_code=$STATUS_CODE" >> $GITHUB_OUTPUT

          echo "----- Response content -----"
          cat response.txt
          echo ""
          echo "----------------------------"

          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "❌ Failed: Expected 200, got $STATUS_CODE"
            exit 1
          fi

          if grep -q '"status":"ok"' response.txt; then
            echo "✅ Success: Status is 'ok'"
            exit 0
          else
            echo "❌ Failed: Expected status 'ok' in JSON response"
            exit 1
          fi
